platform :ios, 8.0
use_frameworks!

target 'RxGank' do
  pod 'Moya'
  pod 'RxSwift', '~>2.3'
  pod 'RxCocoa', '~>2.3'
  pod 'RxDataSources', '~>0.6.1'
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'
  pod 'Kingfisher'
  pod 'SwiftDate'
  pod 'XCGLogger'
  pod 'TransitionTreasury'
  pod 'TransitionTreasury/Animations'
  pod 'SnapKit'
  pod 'SwiftyUserDefaults'
end

target 'ShareToGank' do
  pod 'Alamofire'
end
