platform :ios, 9.0
use_frameworks!

target 'RxGank' do
  pod 'Moya'
  pod 'RxSwift',:git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'develop'
  pod 'RxCocoa',:git => 'https://github.com/ReactiveX/RxSwift.git', :branch => 'develop'
  pod 'RxDataSources',:git => 'https://github.com/RxSwiftCommunity/RxDataSources.git'
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'
  pod 'Kingfisher'
  pod 'SwiftDate'
  pod 'XCGLogger'
  pod 'TransitionTreasury'
  pod 'TransitionTreasury/Animations'
  pod 'SnapKit'
  pod 'SwiftyUserDefaults'
end

target 'ShareToGank' do
  pod 'Alamofire'
end
